apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: route-custom-host
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - create
  - update

oc adm policy add-cluster-role-to-user route-custom-host <username>
